server:
  port: 9099

#DBMS: MySQL (ver. 8.0.28)
#Case sensitivity: plain=lower, delimited=lower
#Driver: MySQL Connector/J (ver. mysql-connector-java-8.0.25 (Revision: 08be9e9b4cba6aa115f9b27b215887af40b159e0), JDBC4.2)
#Ping: 30 ms
#SSL: yes

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_vue
    username: root
    password: "0756"
    driver-class-name: com.mysql.cj.jdbc.Driver

#    druid:
#      driver-class-name: com.alibaba.druid.pool.DruidDataSource
#      initialSize: 10
#      maxActive: 20
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      testWhileIdle: true
#      testOnBorrow: true
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
#      validationQuery: SELECT 1
#      validation-query-timeout: 500
#      filters: stat,wall
#
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: true
#        login-username: admin
#        login-password: 1122

mybatis:
  type-aliases-package: com.syb.po
  mapper-locations: classpath:mapper/*.xml



